# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Setup PROJ
      #   uses: ./.github/actions/setup-proj
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev
          sudo apt-get install -y ffmpeg
          sudo apt-get install -y python3-dev
          sudo apt-get install -y libhdf5-dev

      - name: Install the python dependencies and asilib
        run: |
          # We need to run this command at some point, but need to figure out how to update the lockfile.
          # uv sync --locked --all-extras --dev
          uv sync --all-extras --dev

          uv add flake8 pytest cartopy
          yes | uv pip uninstall shapely  # https://stackoverflow.com/a/52399943
          uv pip install --no-binary :all: shapely

          # install the package in editable mode via uv
          # uv add --editable .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .venv

      - name: Run tests
        run: uv run pytest tests
